name: pseq2site
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.12
  - pytorch::pytorch=1.7.1
  - cudatoolkit=11.0.3
  - mkl=2020.2
  - biopython=1.79
  - rdkit=2021.03.5
  - openbabel=2.4.1
  - transformers=4.29.2
  - sentencepiece=0.1.96
  - protobuf=3.20.1
  - jupyter=1.0.0
  - matplotlib
  - seaborn
  - tqdm